# Generated by Django 6.0.6 on 2026-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
