# Generated by Django 6.0.6 on 2026-06-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_allowed_ips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='allowed_ips',
            new_name='allowed_device_ids',
        ),
    ]
