# Generated by Django 6.0.6 on 2026-07-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_allowed_ips_ticket_allowed_device_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this event is visible to the public.'),
        ),
    ]
