# Generated by Django 6.0.6 on 2026-07-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stream_link',
        ),
        migrations.AddField(
            model_name='ticket',
            name='access_code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
