# Generated by Django 6.0.6 on 2026-07-12 14:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_event_stream_link_ticket_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='access_code',
            field=models.CharField(db_index=True, default=core.models.generate_access_code, max_length=9, unique=True),
        ),
    ]
