# Generated by Django 6.0.6 on 2026-07-12 15:34

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ticket_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=core.models.generate_voucher_code, max_length=20, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage from 1 to 100')),
                ('max_slots', models.PositiveIntegerField(help_text='Maximum number of times this code can be used')),
                ('slots_used', models.PositiveIntegerField(default=0, help_text='Number of times this code has already been used')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.event')),
            ],
        ),
    ]
