# Generated by Django 6.0.6 on 2026-07-20 19:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='username',
            field=models.CharField(blank=True, default=core.models.generate_viewer_username, max_length=50),
        ),
    ]
