# Generated by Django 6.0.6 on 2026-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ticket_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
