# Generated by Django 6.0.6 on 2026-07-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_platform_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
